import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/Header";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import Refresher from "@/components/custom/Refresher";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-manrope antialiased",
          manrope.variable
        )}
      >
        <StoreProvider>
          <Refresher>
            <Header />
            <main>{children}</main>
            <Toaster
              position="top-right"
              richColors
            />{" "}
          </Refresher>
        </StoreProvider>
      </body>
    </html>
  );
}
